# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XqLtmoq1KtWDYFm_GcaNnXCrc6ZH1iJC
"""

n = 6
l = 65
for i in range(1,n):
  for j in range(i):
    print(chr(l) , end = " ")
    l = l+1
  print( )