# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176Wg1WDM_fWvNlbVdnfrwapiq9QbKDj-
"""

n = 6
for i in range(n):
  for j in range(n-i):
    print("*" , end = " ")
  print(" ")