# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XqLtmoq1KtWDYFm_GcaNnXCrc6ZH1iJC
"""

for i in range(65,70):
  for j in range(65,70):
    print(chr(j) , end = " ")
  print( )