# -*- coding: utf-8 -*-
"""sum of a given number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmO0r5qobRWqR_hDL7stswVjcGyLr7Iq
"""

n = 123
num = n
res = 0
while(n!=0):
  div = n%10
  res = res+div
  n = n//10
print(f"sum of a given num :{num} is {res}")