# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJRBUKGRhXMR-lpqhry_qkZ9Ej46Uzmd
"""

n = 121
rev = 0
rslt = n
while(n!=0):
  div = n%10
  rev = rev*10+div
  n = int(n/10)
if(rev == rslt):
  print("it is palindrome")
else:
  print("it is not a palindrome")